/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionbasedatos.interfaces;

import gestionbasedatos.clases.AdminBDListaNegra;
import gestionbasedatos.clases.CifradoMD5;
import gestionbasedatos.clases.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author m2 <linuxitos@gmail.com>
 */
public class ConfCuenta extends javax.swing.JDialog {

    Usuario usr;
    ModificarBD guiInterfaz;
    AdminBDListaNegra adminLista = new AdminBDListaNegra();
    
    /**
     * Creates new form ConfCuenta
     * @param parent
     * @param modal
     */
    public ConfCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Image icon3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/favicon.png"));
        setIconImage(icon3);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });
    }
    
    public ConfCuenta(java.awt.Frame parent, boolean modal, Usuario user, ModificarBD adminGui) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Image icon3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/favicon.png"));
        setIconImage(icon3);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });
        usr=user;
        guiInterfaz=adminGui;
        setNameUser();
        adminLista.obtenerImagenUsuario(jlblImageUser, user);
    }
    
    private void setNameUser(){
        jtxtApellidos.setText(usr.getApellidos());
        jtxtNombre.setText(usr.getNombre());
    }
    
    private void close(){
        jbCancelar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellidos = new javax.swing.JTextField();
        jbActNombre = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpasswsAct = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpasswdNuev = new javax.swing.JPasswordField();
        jpasswdRep = new javax.swing.JPasswordField();
        jbCambiarPasswd = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jlblImageUser = new javax.swing.JLabel();
        jbCambiarImage = new javax.swing.JButton();
        jbEliminarImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración de la cuenta"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jtxtNombre.setText("Nombre");
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyPressed(evt);
            }
        });

        jtxtApellidos.setText("Apellidos");
        jtxtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtApellidosKeyPressed(evt);
            }
        });

        jbActNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbasedatos/png/32x32/refresh.png"))); // NOI18N
        jbActNombre.setText("Actualizar");
        jbActNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbActNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbActNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cambio de contraseña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Contraseña actual");

        jpasswsAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpasswsActKeyPressed(evt);
            }
        });

        jLabel2.setText("Nueva contraseña");

        jLabel3.setText("Repetir contraseña");

        jpasswdNuev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpasswdNuevKeyPressed(evt);
            }
        });

        jpasswdRep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpasswdRepKeyPressed(evt);
            }
        });

        jbCambiarPasswd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbasedatos/png/32x32/refresh.png"))); // NOI18N
        jbCambiarPasswd.setText("Cambiar");
        jbCambiarPasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarPasswdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpasswsAct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpasswdNuev, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpasswdRep, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbCambiarPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCambiarPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpasswdRep)
                    .addComponent(jpasswdNuev)
                    .addComponent(jpasswsAct))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbasedatos/png/32x32/delete.png"))); // NOI18N
        jbCancelar.setText("Cerrar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cambio de imagen de usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jlblImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbasedatos/images/user-not-image.png"))); // NOI18N

        jbCambiarImage.setText("Cambiar");
        jbCambiarImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiarImageActionPerformed(evt);
            }
        });

        jbEliminarImage.setText("Eliminar");
        jbEliminarImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblImageUser)
                .addGap(207, 207, 207)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCambiarImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jlblImageUser, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jbCambiarImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEliminarImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jbActNombre.doClick();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            jbCancelar.doClick();
        }
    }//GEN-LAST:event_jtxtNombreKeyPressed

    private void jtxtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidosKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jbActNombre.doClick();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            jbCancelar.doClick();
        }
    }//GEN-LAST:event_jtxtApellidosKeyPressed

    private void jpasswsActKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpasswsActKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jbCambiarPasswd.doClick();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            jbCancelar.doClick();
        }
    }//GEN-LAST:event_jpasswsActKeyPressed

    private void jpasswdNuevKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpasswdNuevKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jbCambiarPasswd.doClick();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            jbCancelar.doClick();
        }
    }//GEN-LAST:event_jpasswdNuevKeyPressed

    private void jpasswdRepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpasswdRepKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jbCambiarPasswd.doClick();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            jbCancelar.doClick();
        }
    }//GEN-LAST:event_jpasswdRepKeyPressed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        guiInterfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbActNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActNombreActionPerformed
        if(jtxtApellidos.getText().length()>0 && jtxtNombre.getText().length()>0){
            usr.setApellidos(jtxtApellidos.getText().toUpperCase());
            usr.setNombre(jtxtNombre.getText().toUpperCase());
            adminLista.actualizarNombre(usr);
            JOptionPane.showMessageDialog(null, "Nombre actualizado.","Actualizando",JOptionPane.INFORMATION_MESSAGE);
            guiInterfaz.setUserData();
        }else{
            JOptionPane.showMessageDialog(null, "Rellene los campos vacíos.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbActNombreActionPerformed

    private void jbCambiarPasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarPasswdActionPerformed
        if(CifradoMD5.Cifrado((new String(jpasswsAct.getPassword()))).equals(usr.getPasswd())){
            if((new String(jpasswdNuev.getPassword())).equals(new String (jpasswdRep.getPassword()))){
                if(jpasswdNuev.getPassword().length>0){
                    usr.setPasswd(CifradoMD5.Cifrado(new String (jpasswdNuev.getPassword())));
                    adminLista.cambiarPasswd(usr);
                    jpasswdNuev.setText("");
                    jpasswdRep.setText("");
                    jpasswsAct.setText("");
                    JOptionPane.showMessageDialog(null, "Contraseña actualizada.","Actualizando",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "La contraseña no puede ser vacía.","Error", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Las contraseñas nuevas no coinciden.","Error", JOptionPane.ERROR_MESSAGE);
                jpasswdNuev.setText("");
                jpasswdRep.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "La contraseña actual no coincide.","Error", JOptionPane.ERROR_MESSAGE);
            jpasswsAct.setText("");
        }
    }//GEN-LAST:event_jbCambiarPasswdActionPerformed

    private void jbCambiarImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiarImageActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Archivos png & jpg", "png", "jpg");
        chooser.setFileFilter(filter);
        String userHome = System.getProperty( "user.home" );
        chooser.setCurrentDirectory(new File(userHome));
        chooser.setAcceptAllFileFilterUsed(false);
        int retrival = chooser.showOpenDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                String pathImage = chooser.getSelectedFile().getAbsolutePath();
                adminLista.actualizarImagenUsuario(usr, pathImage);
                adminLista.obtenerImagenUsuario(jlblImageUser, usr);
                adminLista.obtenerImagenUsuario(guiInterfaz.getJlblImage(), usr);
            } catch (Exception ex) {
                System.err.println("Error al abrir el archivo: " +ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbCambiarImageActionPerformed

    private void jbEliminarImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarImageActionPerformed
        int confirmar=JOptionPane.showConfirmDialog(null,"¿Eliminar la imagen de usuario?");
        if(confirmar==0){
            adminLista.eliminarImagenUsuario(usr);
            JOptionPane.showMessageDialog( null,"Imagen de usuario eliminada","Eliminando Imagen de Usuario",JOptionPane.INFORMATION_MESSAGE);
            adminLista.obtenerImagenUsuario(jlblImageUser, usr);
            adminLista.obtenerImagenUsuario(guiInterfaz.getJlblImage(), usr);
        }else{
            JOptionPane.showMessageDialog( null,"Eliminanción cancelada","Eliminando Imagen",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbEliminarImageActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbActNombre;
    private javax.swing.JButton jbCambiarImage;
    private javax.swing.JButton jbCambiarPasswd;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminarImage;
    private javax.swing.JLabel jlblImageUser;
    private javax.swing.JPasswordField jpasswdNuev;
    private javax.swing.JPasswordField jpasswdRep;
    private javax.swing.JPasswordField jpasswsAct;
    private javax.swing.JTextField jtxtApellidos;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
}
