/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionbasedatos.interfaces;

import gestionbasedatos.clases.AdminBDListaNegra;
import gestionbasedatos.clases.FuncionesBD;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author m2 <linuxitos@gmail.com>
 */
public class RestoreBackupBD extends javax.swing.JDialog {

    private final AdminBDListaNegra adminBD;
    public ModificarBD guiAdminBD;

    /**
     * Creates new form RestoreBackupBD
     * @param parent
     * @param modal
     * @param admin
     */
    public RestoreBackupBD(java.awt.Frame parent, boolean modal, AdminBDListaNegra admin) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Image icon3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/favicon.png"));
        setIconImage(icon3);
        this.adminBD = admin;
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });
        this.guiAdminBD = (ModificarBD) parent;
    }
    
    private void close(){
        guiAdminBD.setVisible(true);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbRespaldo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Respaldo y Restauración de la Base de Datos"));

        jLabel1.setText("Respaldar la Base de Datos");

        jbRespaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbasedatos/png/32x32/text_page.png"))); // NOI18N
        jbRespaldo.setText("Respaldo");
        jbRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRespaldoActionPerformed(evt);
            }
        });

        jLabel2.setText("Restaurar la Base de Datos");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbasedatos/png/32x32/download.png"))); // NOI18N
        jButton1.setText("Restaurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbasedatos/png/32x32/delete.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbRespaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbRespaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRespaldoActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Archivos sql", "sql");
        chooser.setFileFilter(filter);
        String userHome = System.getProperty( "user.home" );
        chooser.setCurrentDirectory(new File(userHome));
        chooser.setAcceptAllFileFilterUsed(false);
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                String archivoSql = chooser.getSelectedFile()+".sql";
                if (!archivoSql.contains(".sql")) {
                    archivoSql = archivoSql + ".sql";
                }
                FuncionesBD resp = new FuncionesBD(adminBD.getConectarBD().getBd(), 
                        adminBD.getConectarBD().getUsuario(),
                        adminBD.getConectarBD().getContrasena(), archivoSql);
                resp.backupDB();
            } catch (Exception ex) {
                System.err.println("Error guardando archivo: " +ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbRespaldoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Archivos sql", "sql");
        chooser.setFileFilter(filter);
        String userHome = System.getProperty( "user.home" );
        chooser.setCurrentDirectory(new File(userHome));
        chooser.setAcceptAllFileFilterUsed(false);
        int retrival = chooser.showOpenDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                String archivoSql = chooser.getSelectedFile()+"";
                if (!archivoSql.contains(".sql")) {
                    archivoSql = archivoSql + ".sql";
                }
                FuncionesBD resp = new FuncionesBD(adminBD.getConectarBD().getBd(), 
                        adminBD.getConectarBD().getUsuario(),
                        adminBD.getConectarBD().getContrasena(), archivoSql);
                File file = new File(archivoSql);
                String path = file.getPath();
                int confirmar;
                confirmar=JOptionPane.showConfirmDialog(null,"La información de la Base de Datos será reemplazada. ¿Desea continuar?");
                if(confirmar==0){
                    resp.restoreDB(file);
                }else{
                    JOptionPane.showMessageDialog( null,"Restauración cancelada.","Restaurar BD",JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                System.err.println("Error al abrir el archivo: " +ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbRespaldo;
    // End of variables declaration//GEN-END:variables
}
