/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionbasedatos.interfaces;

import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author m2 <linuxitos@gmail.com>
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        Image icon3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/favicon.png"));
        setIconImage(icon3);
        setLocationRelativeTo(null);
        jProgressInicio.setMinimum(0);
        jProgressInicio.setMaximum(100);
        jProgressInicio.setStringPainted(true);
        
        Thread t = new Thread() {
            @Override
            @SuppressWarnings("SleepWhileInLoop")
            public void run() {
                int i = 0;
                while (i <= 100) {
                    jProgressInicio.setValue(i);
                    if(i==0){
                        jlblMensaje.setText("Cargando componente de intergaz...");
                    }
                    if(i==23){
                        jlblMensaje.setText("Comprobando base de datos...");
                    }
                    if(i==67){
                        jlblMensaje.setText("Cargando archivos de configuración...");
                    }
                    if(i==90){
                        jlblMensaje.setText("Bienvenido al Sistema...");
                    }
                    try {
                        sleep(90);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    i++;
                }
            }
        };
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblMensaje = new javax.swing.JLabel();
        jProgressInicio = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jlblMensaje.setForeground(new java.awt.Color(254, 254, 254));
        jlblMensaje.setText("jLabel2");
        jPanel1.add(jlblMensaje);
        jlblMensaje.setBounds(10, 180, 360, 15);
        jPanel1.add(jProgressInicio);
        jProgressInicio.setBounds(10, 200, 360, 20);

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("v2.3.7");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(337, 80, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbasedatos/images/splashScreenA.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 503, 253);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressInicio;
    private javax.swing.JLabel jlblMensaje;
    // End of variables declaration//GEN-END:variables
}
